ecommerce_website/account/urls.py
from django.urls import path
from . import views
app_name='account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

ecommerce_website/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summery, name='cart_summery'),
    path('add/', views.cart_add, name='cart_add'),
    path('update/', views.cart_update, name='cart_update'),
    path('delete/', views.cart_delete, name='cart_delete'),

]

ecommerce_website/ecommerce_website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls',namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('cart/',include('cart.urls',namespace='cart')),

]

ecommerce_website/shop/urls.py
from django.urls import path
from . import views
app_name ='shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('shop/', views.admin_dashboard, name='admin_dashboard'),
    path('shop/category/add/', views.add_category, name='add_category'),
    path('shop/category/update/<int:pk>/', views.update_category, name='update_category'),
    path('shop/category/delete/<int:pk>/', views.delete_category, name='delete_category'),
    path('shop/product/add/', views.add_product, name='add_product'),
    path('shop/product/update/<int:pk>/', views.update_product, name='update_product'),
    path('shop/product/delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('shop/category/<int:pk>/', views.category_detail, name='category_detail'),
]

ecommerce_website/shop/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name =models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    def __str__(self):
        return self.name
    

ecommerce_website/shop/forms.py
from django import forms
from .models import Category,Product

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name','description']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['category','name','description','price','stock']
        

ecommerce_website/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Category, Product
from django.urls import reverse
from .forms import CategoryForm, ProductForm
from django.contrib.auth.decorators import user_passes_test



def admin_required(user):
    return user.is_superuser

@user_passes_test(admin_required)
def admin_dashboard(request):
    categories = Category.objects.all()
    products = Product.objects.all()
    return render(request, 'shop/admin_dashboard.html', {'categories': categories, 'products': products})

@user_passes_test(admin_required)
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('shop:admin_dashboard'))
    else:
        form = CategoryForm()
    return render(request, 'shop/add_category.html', {'form': form})

@user_passes_test(admin_required)
def update_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect(reverse('shop:admin_dashboard'))
    else:
        form = CategoryForm(instance=category)
    return render(request, 'shop/update_category.html', {'form': form,'pk':pk})

@user_passes_test(admin_required)
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        return redirect(reverse('shop:admin_dashboard'))

    return render(request, 'shop/delete_category.html', {'category': category,'pk':pk})

@user_passes_test(admin_required)
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('shop:admin_dashboard'))
    else:
        form = ProductForm()
    return render(request, 'shop/add_product.html', {'form': form})

@user_passes_test(admin_required)
def update_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect(reverse('shop:admin_dashboard'))
    else:
        form = ProductForm(instance=product)
    return render(request, 'shop/update_product.html', {'form': form,'pk':pk})

@user_passes_test(admin_required)
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        return redirect(reverse('shop:admin_dashboard'))
    return render(request, 'shop/delete_product.html', {'product': product,'pk':pk})

def index(request):
    categories = Category.objects.all()
    return render(request, 'shop/index.html', {'categories': categories})

def category_detail(request, pk):
    category = get_object_or_404(Category, pk=pk)
    products = Product.objects.filter(category=category)
    return render(request, 'shop/category_detail.html', {'category': category, 'products': products})

ecommerce_website/shop/templates/shop/add_category.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Category</title>
</head>
<body>
    <h1>Add Category</h1>
    <form  action="{% url 'shop:add_category' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
    <a href="{% url 'shop:admin_dashboard' %}">Back to Dashboard</a>
</body>
</html>

ecommerce_website/shop/templates/shop/add_product.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Product</title>
</head>
<body>
    <h1>Add Product</h1>
    <form  action="{% url 'shop:add_product' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
    <a href="{% url 'shop:admin_dashboard' %}">Back to Dashboard</a>
</body>
</html>

ecommerce_website/shop/templates/shop/admin_dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Admin Dashboard</title>
</head>
<body>
    <h1>Admin Dashboard</h1>
    <a href="{% url 'shop:add_category' %}">Add Category</a>
    <a href="{% url 'shop:add_product' %}">Add Product</a>
    <h2>Categories</h2>
    <ul>
        {% for category in categories %}
        <li>
            {{ category.name }}
            <a href="{% url 'shop:update_category' pk=category.pk %}">Edit</a>
            <a href="{% url 'shop:delete_category' pk=category.pk %}">Delete</a>
        </li>
        {% endfor %}
    </ul>
    <h2>Products</h2>
    <ul>
        {% for product in products %}
        <li>
            {{ product.name }}
            <a href="{% url 'shop:update_product' pk=product.pk %}">Edit</a>
            <a href="{% url 'shop:delete_product' pk=product.pk %}">Delete</a>
        </li>
        {% endfor %}
    </ul>
</body>
</html>

ecommerce_website/shop/templates/shop/category_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Products in {{ category.name }}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <h3><a href="{% url 'cart:cart_summery' %}"> cart 
    <span id="cart_quantity">{{ cart|length }}</span> </a></h3>
    <h1>Products in {{ category.name }}</h1>
    <ul>
        {% for product in products %}
        <li>
            {{ product.name }}
            <hr>
            {{ product.description }} - {{ product.price }} {{ product.id }}
            <br>
            <input type="number" class="product-quantity" value="1" min="1" max="8" data-product-id="{{ product.id }}">
            <button type="button" value="{{ product.id }}" class="add-cart">Add to Cart</button>
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'shop:index' %}">Back to Categories</a>
    <script>
        $(document).on('click', ".add-cart", function(e) {
            e.preventDefault();
            var product_id = $(this).val();
            var quantity = $('.product-quantity[data-product-id="' + product_id + '"]').val();
            $.ajax({
                type: 'POST',
                url: '{% url "cart:cart_add" %}',
                data: {
                    product_id: product_id,
                    quantity: quantity,  // Include quantity
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function(json) {
                    console.log(json);
                    document.getElementById("cart_quantity").textContent = json.cart_quantity;
                },
                error: function(xhr, errmsg, err) {
                    console.log(errmsg);
                }
            });
        });
        
    </script>
</body>
</html>

ecommerce_website/shop/templates/shop/delete_category.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Category</title>
</head>
<body>
    <h1>Delete Category</h1>
    <p>Are you sure you want to delete {{ category.name }}?</p>
    <form action="{% url 'shop:delete_category' pk=pk %}" method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
    <a href="{% url 'shop:admin_dashboard' %}">Back to Dashboard</a>
</body>
</html>

ecommerce_website/shop/templates/shop/delete_product.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Product</title>
</head>
<body>
    <h1>Delete Product</h1>
    <p>Are you sure you want to delete {{ product.name }}?</p>
    <form action="{% url 'shop:delete_product' pk=pk%}" method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
    <a href="{% url 'shop:admin_dashboard' %}">Back to Dashboard</a>
</body>
</html>

ecommerce_website/shop/templates/shop/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Categories</title>
</head>
<body>
    <h1>Categories</h1>
    <ul>
        {% for category in categories %}
        <li>
            <a href="{% url 'shop:category_detail' category.pk %}">{{ category.name }}</a>
            <p>{{category.description}}
            </p>
        </li>
        {% endfor %}
    </ul>
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
        <a href="{% url 'shop:add_category' %}"><button>Add Category</button></a>
        <a href="{% url 'shop:add_product' %}"><button>Add Product</button></a>
        {% endif %}
        <a href="{% url 'account:logout' %}"><button>Logout</button></a>
    {% else %}
        <a href="{% url 'account:login' %}"><button>Login</button></a>
        <a href="{% url 'account:signup' %}"><button>Sign Up</button></a>
    {% endif %}
    
</body>
</html>

ecommerce_website/shop/templates/shop/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    {% if messages %}
        {% for message in messages %}
            <p style="color: red;">{{ message }}</p>
        {% endfor %}
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required><br><br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br><br>
        <button type="submit">Login</button>
    </form>
</body>
</html>

ecommerce_website/shop/templates/shop/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign Up</title>
</head>
<body>
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign Up</button>
    </form>
</body>
</html>

ecommerce_website/shop/templates/shop/update_category.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Category</title>
</head>
<body>
    <h1>Update Category</h1>
    <form action = "{% url 'shop:update_category' pk=pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    <a href="{% url 'shop:admin_dashboard' %}">Back to Dashboard</a>
</body>
</html>

ecommerce_website/shop/templates/shop/update_product.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Product</title>
</head>
<body>
    <h1>Update Product</h1>
    <form action = "{% url 'shop:update_product' pk=pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    <a href="{% url 'shop:admin_dashboard' %}">Back to Dashboard</a>
</body>
</html>